name: Validate JSON
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check JSON
        run: |
          for f in $(git ls-files 'submissions/**/*.json'); do
            python -m json.tool $f > /dev/null; done